import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { useEffect, useState } from "react";
import { toast } from "sonner";

function localDateTime(date: Date) { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 16); }

export function EmailLogDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const leads = trpc.leads.list.useQuery(undefined);
  const clients = trpc.clients.list.useQuery();
  const utils = trpc.useUtils();
  const [form, setForm] = useState({ link: "none", direction: "outbound", fromAddress: "bigbluemop@gmail.com", toAddress: "", subject: "", snippet: "", sentAt: "" });
  const log = trpc.workspace.logEmail.useMutation();
  useEffect(() => { if (open) setForm({ link: "none", direction: "outbound", fromAddress: "bigbluemop@gmail.com", toAddress: "", subject: "", snippet: "", sentAt: localDateTime(new Date()) }); }, [open]);
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const selectLink = (value: string) => { set("link", value); const [kind, rawId] = value.split(":"); const id = Number(rawId); const record = kind === "lead" ? leads.data?.find(item => item.id === id) : clients.data?.find(item => item.id === id); if (record?.email) set("toAddress", record.email); };
  const submit = async (openMail: boolean) => { const [kind, rawId] = form.link.split(":"); const id = Number(rawId); try { await log.mutateAsync({ leadId: kind === "lead" ? id : null, clientId: kind === "client" ? id : null, direction: form.direction as "inbound" | "outbound", fromAddress: form.fromAddress.trim() || null, toAddress: form.toAddress.trim() || null, subject: form.subject.trim() || null, snippet: form.snippet.trim() || null, sentAt: new Date(form.sentAt) }); await Promise.all([utils.workspace.emailActivity.invalidate(), utils.leads.timeline.invalidate()]); toast.success("Email activity logged"); onOpenChange(false); if (openMail && form.toAddress) window.location.href = `mailto:${encodeURIComponent(form.toAddress)}?subject=${encodeURIComponent(form.subject)}&body=${encodeURIComponent(form.snippet)}`; } catch (error) { toast.error(error instanceof Error ? error.message : "Email could not be logged"); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle className="font-display text-2xl uppercase">Log email follow-up</DialogTitle><DialogDescription>Record inbound or outbound email activity against a lead or client. Outbound mail can open in your normal mail application.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label>Linked record</Label><Select value={form.link} onValueChange={selectLink}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No linked record</SelectItem>{leads.data?.map(lead => <SelectItem key={`lead:${lead.id}`} value={`lead:${lead.id}`}>Lead · {lead.businessName}</SelectItem>)}{clients.data?.map(client => <SelectItem key={`client:${client.id}`} value={`client:${client.id}`}>Client · {client.businessName}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Direction</Label><Select value={form.direction} onValueChange={value => set("direction", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="outbound">Outbound</SelectItem><SelectItem value="inbound">Inbound</SelectItem></SelectContent></Select></div><Field label="Date and time" type="datetime-local" value={form.sentAt} onChange={value => set("sentAt", value)} /><Field label="From" type="email" value={form.fromAddress} onChange={value => set("fromAddress", value)} /><Field label="To" type="email" value={form.toAddress} onChange={value => set("toAddress", value)} /><div className="space-y-2 sm:col-span-2"><Label>Subject</Label><Input value={form.subject} onChange={event => set("subject", event.target.value)} /></div><div className="space-y-2 sm:col-span-2"><Label>Message or snippet</Label><Textarea rows={6} value={form.snippet} onChange={event => set("snippet", event.target.value)} /></div></div><DialogFooter className="flex-col sm:flex-row"><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="outline" onClick={() => submit(false)} disabled={log.isPending || !form.sentAt}>Log only</Button>{form.direction === "outbound" ? <Button onClick={() => submit(true)} disabled={log.isPending || !form.sentAt || !form.toAddress}>Log & open mail app</Button> : null}</DialogFooter></DialogContent></Dialog>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <div className="space-y-2"><Label>{label}</Label><Input type={type} value={value} onChange={event => onChange(event.target.value)} /></div>; }
