import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type ClientOption = { id: number; businessName: string };
function asDate(value: string) { return value ? new Date(`${value}T00:00:00`) : null; }

export function InvoiceFormDialog({ open, onOpenChange, clients, fixedClientId }: { open: boolean; onOpenChange: (open: boolean) => void; clients: ClientOption[]; fixedClientId?: number }) {
  const [form, setForm] = useState({ clientId: "", invoiceNumber: "", amount: "", status: "outstanding", issuedAt: "", sentAt: "", dueAt: "", paidAt: "", notes: "" });
  const utils = trpc.useUtils();
  useEffect(() => { if (open) { const today = new Date().toISOString().slice(0, 10); const due = new Date(); due.setDate(due.getDate() + 14); setForm({ clientId: fixedClientId?.toString() ?? clients[0]?.id.toString() ?? "", invoiceNumber: "", amount: "", status: "outstanding", issuedAt: today, sentAt: today, dueAt: due.toISOString().slice(0, 10), paidAt: "", notes: "" }); } }, [open, fixedClientId, clients]);
  const create = trpc.finance.createInvoice.useMutation({ onSuccess: async () => { toast.success("Invoice saved"); await Promise.all([utils.finance.listInvoices.invalidate(), utils.finance.overview.invalidate(), utils.dashboard.summary.invalidate(), fixedClientId ? utils.clients.get.invalidate({ id: fixedClientId }) : Promise.resolve()]); onOpenChange(false); }, onError: error => toast.error(error.message) });
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const submit = () => create.mutate({ clientId: Number(form.clientId), invoiceNumber: form.invoiceNumber.trim(), amountCents: Math.round(Number(form.amount) * 100), status: form.status as "draft" | "sent" | "outstanding" | "paid" | "overdue" | "void", issuedAt: asDate(form.issuedAt), sentAt: asDate(form.sentAt), dueAt: asDate(form.dueAt), paidAt: form.status === "paid" ? asDate(form.paidAt || form.sentAt) : null, notes: form.notes.trim() || null });
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle className="font-display text-2xl uppercase">Add invoice</DialogTitle><DialogDescription>Capture invoice number, amount, sent date and payment status.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Client</Label><Select value={form.clientId} onValueChange={value => set("clientId", value)} disabled={Boolean(fixedClientId)}><SelectTrigger><SelectValue placeholder="Select client" /></SelectTrigger><SelectContent>{clients.map(client => <SelectItem key={client.id} value={client.id.toString()}>{client.businessName}</SelectItem>)}</SelectContent></Select></div><Field label="Invoice number" value={form.invoiceNumber} onChange={value => set("invoiceNumber", value)} /><Field label="Amount (AUD)" type="number" value={form.amount} onChange={value => set("amount", value)} /><div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={value => set("status", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">Draft</SelectItem><SelectItem value="sent">Sent</SelectItem><SelectItem value="outstanding">Outstanding</SelectItem><SelectItem value="paid">Paid</SelectItem><SelectItem value="overdue">Overdue</SelectItem><SelectItem value="void">Void</SelectItem></SelectContent></Select></div><Field label="Issued date" type="date" value={form.issuedAt} onChange={value => set("issuedAt", value)} /><Field label="Sent date" type="date" value={form.sentAt} onChange={value => set("sentAt", value)} /><Field label="Due date" type="date" value={form.dueAt} onChange={value => set("dueAt", value)} />{form.status === "paid" ? <Field label="Paid date" type="date" value={form.paidAt} onChange={value => set("paidAt", value)} /> : <div/>}<div className="space-y-2 sm:col-span-2"><Label>Notes</Label><Textarea rows={3} value={form.notes} onChange={event => set("notes", event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={submit} disabled={!form.clientId || !form.invoiceNumber.trim() || !(Number(form.amount) > 0) || create.isPending}>{create.isPending ? "Saving..." : "Save invoice"}</Button></DialogFooter></DialogContent></Dialog>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <div className="space-y-2"><Label>{label}</Label><Input type={type} min={type === "number" ? "0" : undefined} step={type === "number" ? "0.01" : undefined} value={value} onChange={event => onChange(event.target.value)} /></div>; }
